micronaut:
  application:
    name: hackathon
#database configuration
datasources:
  default:
    url: ${HACKATHON_JDBC_URL:`jdbc:h2:./data/db;MODE=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${HACKATHON_JDBC_USER:sa}
    password: ${HACKATHON_JDBC_PASSWORD:""}
    driverClassName: ${HACKATHON_JDBC_DRIVER:org.h2.Driver}

#hibernate
jpa:
  default:
    packages-to-scan:
      - 'hackathon.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: ${HIBERNATE_DIALECT:`org.hibernate.dialect.H2Dialect`}
