export HACKATHON_JDBC_URL='jdbc:mysql://ghack2020db.cqdnabcbucma.eu-west-1.rds.amazonaws.com:3306/gdphack2020db'
export HACKATHON_JDBC_USER='admin'
export HACKATHON_JDBC_PASSWORD='GDPHack2020'
export HACKATHON_JDBC_DRIVER='com.mysql.cj.jdbc.Driver'
export HIBERNATE_DIALECT='org.hibernate.dialect.MySQL8Dialect'
